package io.finmsg.dmn.ir;

public enum RuntimeTypeKind {
	ANY, NULL, BOOLEAN, NUMBER, STRING, DATE, TIME, DATE_TIME, DURATION, YEARS_MONTHS_DURATION, DAYS_TIME_DURATION, LIST, RANGE, CONTEXT, FUNCTION
}
